### ISSUE TITLE
Minor errors in getting-started documentation

### ISSUE THREAD

**Issue by Const-me** [jkoritzinsky/SharpGenTools#29]
To install the packages, I had to run following:

    Install-Package SharpGenTools.Sdk -Version 1.0.0-rc1
    Install-Package SharpGen.Runtime -Version 1.0.0-rc1

Another one, apparently the config XML must be `<config id="MyMapping" xmlns="urn:SharpGen.Config">`, not `<config id="MyMapping" xmlns:urn="SharpGen.Config">`

**Comment by jkoritzinsky** [comment]
Good catch! I'm not going to add the `Version` attribute because this documentation is for the upcoming 1.0.0 release (there were a few bugs fixed in the interim), but the config XML fix I'll definitely do!
