### ISSUE TITLE
CastXml error when building... 

### ISSUE THREAD

**Issue by danwalmsley** [jkoritzinsky/SharpGenTools#31]
castxml error : C++ Header file [C:\dev\repos\AvalonStudio\AvalonStudio\CorApi.Portable/obj\Debug\netstandard1.5\SharpGen/SharpGen-MSBuild.h] not found

2>C:\Users\danw\.nuget\packages\sharpgentools.sdk\1.0.0-rc1\build\SharpGenTools.Sdk.targets(140,5): error : A fatal error occured
2>C:\Users\danw\.nuget\packages\sharpgentools.sdk\1.0.0-rc1\build\SharpGenTools.Sdk.targets(140,5): error : A fatal error occurred

Any ideas whats going on?

**Comment by danwalmsley** [comment]
Started happening since I cleared out my nuget cache.

**Comment by jkoritzinsky** [comment]
Can you try the ci build from MyGet and see if you still have the same issue?

**Comment by danwalmsley** [comment]
that fixes it :) thanks
